"""Data contracts for a reasoning audit.

Every value the AI produces is validated against these models, so the frontend
can render structured findings instead of parsing prose.
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class BlindSpotKind(str, Enum):
    """The six ways reasoning can be incomplete."""

    SALIENCE = "salience"
    ASSUMPTION = "assumption"
    OMISSION = "omission"
    CONFLICT = "conflict"
    PERSPECTIVE = "perspective"
    UNCERTAINTY = "uncertainty"


class EvidenceLevel(str, Enum):
    """How well supported a belief is, judged from what the user provided."""

    NONE = "none"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class Importance(str, Enum):
    """How much the belief matters to the decision."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class AuditRequest(BaseModel):
    """What the user tells us before the audit runs."""

    decision: str = Field(
        min_length=3,
        max_length=2000,
        description="The decision being considered.",
    )
    leaning: str = Field(
        default="",
        max_length=1000,
        description="What the user is currently leaning toward, if anything.",
    )
    reasons: str = Field(
        min_length=3,
        max_length=8000,
        description="Why the user is leaning that way, in their own words.",
    )
    priorities: str = Field(
        default="",
        max_length=2000,
        description="What matters most to the user in this decision.",
    )


class DimensionScore(BaseModel):
    """How much attention one decision dimension received."""

    key: str
    label: str
    mentions: int
    share: float = Field(ge=0.0, le=1.0, description="Share of all matched mentions.")


class SalienceReport(BaseModel):
    """Deterministic attention analysis, computed in Python without an LLM."""

    total_mentions: int
    emphasised: list[DimensionScore] = Field(
        default_factory=list,
        description="Dimensions carrying most of the user's attention.",
    )
    silent: list[DimensionScore] = Field(
        default_factory=list,
        description="Dimensions with no mention at all.",
    )
    note: str = Field(default="", description="Plain-language summary of the imbalance.")


class BlindSpot(BaseModel):
    """One gap found in the reasoning."""

    kind: BlindSpotKind
    title: str = Field(max_length=120)
    detail: str = Field(max_length=1200)
    evidence: str = Field(
        default="",
        max_length=600,
        description="The user's own words this finding is based on.",
    )
    question: str = Field(max_length=400)
    impact: int = Field(ge=1, le=5)
    uncertainty: int = Field(ge=1, le=5)

    @property
    def priority(self) -> int:
        """Rank findings by impact weighted by how little is known."""
        return self.impact * self.uncertainty


class Assumption(BaseModel):
    """A belief the reasoning rests on, with its support judged."""

    statement: str = Field(max_length=400)
    evidence_level: EvidenceLevel
    importance: Importance
    question: str = Field(max_length=400)

    @property
    def is_critical(self) -> bool:
        """A critical assumption matters a lot and is weakly supported."""
        return (
            self.importance == Importance.HIGH
            and self.evidence_level in (EvidenceLevel.NONE, EvidenceLevel.LOW)
        )


class WorthwhileQuestion(BaseModel):
    """A question ranked by how much its answer could change the reasoning."""

    text: str = Field(max_length=400)
    why: str = Field(max_length=400)
    impact: int = Field(ge=1, le=5)
    uncertainty: int = Field(ge=1, le=5)

    @property
    def priority(self) -> int:
        """Answering this could matter, and the user does not know it yet."""
        return self.impact * self.uncertainty


class AuditResult(BaseModel):
    """The complete audit returned to the client."""

    restatement: str = Field(
        max_length=800,
        description="A neutral summary of the user's reasoning, in their terms.",
    )
    salience: SalienceReport
    blind_spots: list[BlindSpot] = Field(min_length=1, max_length=8)
    assumptions: list[Assumption] = Field(min_length=1, max_length=10)
    questions: list[WorthwhileQuestion] = Field(min_length=1, max_length=6)
    closing: str = Field(
        max_length=600,
        description="A neutral closing that returns the decision to the user.",
    )


class StoredAuditSummary(BaseModel):
    """A saved audit as listed or reopened from storage.

    Only the summary is stored. Findings are regenerated by running a fresh
    audit, so a re-opened decision always reflects current reasoning.
    """

    audit_id: str
    created_at: str
    decision: str
    restatement: str
    blind_spot_count: int
    assumption_count: int
    reasons: str = ""
    priorities: str = ""
    leaning: str = ""


class SilenceFinding(BaseModel):
    """One dimension the user keeps leaving out across their decisions."""

    label: str
    missed_in: int
    total_audits: int

    @property
    def miss_rate(self) -> float:
        """Share of audits where this dimension drew no attention."""
        return (self.missed_in / self.total_audits) if self.total_audits else 0.0


class SilenceReport(BaseModel):
    """A cross-decision view of what the user habitually overlooks.

    Each audit is a single decision, so one silence is weak evidence. A
    dimension missed across many decisions is a pattern worth showing.
    """

    total_audits: int
    findings: list[SilenceFinding] = Field(default_factory=list)
    note: str = ""
